# Generated by Django 4.2.6 on 2023-10-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_generator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcode",
            name="barcode",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
