# Generated by Django 4.2.6 on 2023-10-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_generator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skuinformation",
            name="barcode",
        ),
        migrations.AddField(
            model_name="skuinformation",
            name="barcode",
            field=models.ManyToManyField(to="order_generator.barcode"),
        ),
    ]
