# Generated by Django 4.2.6 on 2023-10-18 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order_generator", "0002_alter_barcode_barcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkuInformationBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_generator.barcode",
                    ),
                ),
                (
                    "sku_information",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order_generator.skuinformation",
                    ),
                ),
            ],
        ),
    ]
