# Generated by Django 4.2.6 on 2023-10-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "order_generator",
            "0002_remove_skuinformation_barcode_skuinformation_barcode",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="skuinformation",
            name="barcode",
            field=models.ManyToManyField(null=True, to="order_generator.barcode"),
        ),
    ]
