# Generated by Django 4.2.6 on 2023-10-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order_generator", "0003_skuinformationbarcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="recorded_to_ds",
            field=models.BooleanField(default=False),
        ),
    ]
